### ISSUE TITLE
Issue with directory structure of the release

### ISSUE THREAD

**Issue by Zero3K** [T3aHat/DeepLopener#1]
It starts with a folder (which makes it impossible to install it via drag and drop). Please compress the files in the directory and not the directory itself.

**Comment by T3aHat** [comment]
Thank you for your valuable advice!
I added a zip file.
https://github.com/T3aHat/DeepLopener/releases/download/0.2.0/DeepLopener.zip

And,I'll try to implement your other suggestions as well.
Unfortunately,I tried to hide DeepL tabs, but I couldn't find an idea of good implementation...
Sorry.

**Comment by Zero3K** [comment]
Thanks. This issue is fixed then.
