### ISSUE TITLE
Console log of "DeepLopener: loaded" to disappear

### ISSUE THREAD

**Issue by shu-pf** [T3aHat/DeepLopener#10]
Thanks for the great product.

I do a lot of debugging in the console log, so I want the console log of "DeepLopener: loaded" to disappear.

**Comment by shu-pf** [comment]
It would be nice if you could hide the console log with an environment variable or something.

**Comment by T3aHat** [comment]
Thank you for your good comment.  
I removed the console log (dd3d7faef0d6b9710ea763c6c97ce5df70f6ef63).
