### ISSUE TITLE
拡張機能に対してショートカットを設定したい

### ISSUE THREAD

**Issue by shu-pf** [T3aHat/DeepLopener#11]
chromeで拡張機能に対するショートカットを
chrome://extensions/shortcuts
にて設定できるのですが、このプラグインでは設定が出来ないようです。

layout-oriented replacement modeを起動する際にマウス移動が必要になるので、
ショートカットを設定できれば大変有り難いです。

バージョン: 1.2.8

**Comment by T3aHat** [comment]
コメントありがとうございます．
早速実装させていただきました！ ( a5aa584e97d6a71d008bad40d0eb7933fc249af8 )
![image](https://user-images.githubusercontent.com/36735403/151158222-e086eb06-e27e-4668-967b-592d34cc68b0.png)

ドキュメントの更新や動画の準備が完了次第ChromeWebStoreの方で更新するので今しばらくお待ちください．

**Comment by shu-pf** [comment]
有り難うございます！
これのお陰で英語のドキュメントを読むのが早くなり本当に助かってます。
ChromeWebStoreでの更新楽しみにしておきます。
