### ISSUE TITLE
No LICENSE?

### ISSUE THREAD

**Issue by aaaaninja** [T3aHat/DeepLopener#12]
日本人の方だと思うので日本語で失礼します。

日頃ありがたくこの拡張機能を使用させていただいてます。
ライセンスをこのリポジトリに設定していないのは意図的でしょうか？

というのもソースコードも公開されていますがライセンスが特に設定されていないので、仮にプルリクなどで貢献しようとしても現状できない状態かと思っています。

**Comment by T3aHat** [comment]
返信が遅れてしまい申し訳ございません．
コメントいただきありがとうございます．
本リポジトリはMITライセンスとしました (911e6489e84f4493e9aad1abd7a377fe156417a2) ．
