### ISSUE TITLE
Hide DeepL tab when translating via automated methods

### ISSUE THREAD

**Issue by Zero3K** [T3aHat/DeepLopener#2]
It would be nice if it could hide the DeepL tab when translating via automated methods.

**Comment by T3aHat** [comment]
On [v0.5.0](https://github.com/T3aHat/DeepLopener/commit/5291e3b7ac0d49dcc613154d5f1a23a8fe0aeb3d), DeepL tabs are opened on other windows that is non-active and minimized.  
This makes it look a little better.

**Comment by T3aHat** [comment]
On [v0.5.4](https://github.com/T3aHat/DeepLopener/commit/0715b56944a3ca9280cdd6dc7292de2d76f94f02), when incognito mode enabled, tabs will be opened on "Incongnito mode" and DeepL's history won't be saved.
That's all I can do now.
