### ISSUE TITLE
Keep style of website when translating selected text

### ISSUE THREAD

**Issue by Zero3K** [T3aHat/DeepLopener#5]
It would be nice if it kept the style of the website when translating selected text. I noticed it not doing that when I translated text in a Twitter DM.

**Comment by T3aHat** [comment]
On [v1.2.0](https://github.com/T3aHat/DeepLopener/commit/79a9615b45a773a4ce9d18a4870601bf2a81164d), I implemented `tag-handling replacement mode` that translate text keeping the original style.
