### ISSUE TITLE
特定のページで表示が崩れます

### ISSUE THREAD

**Issue by cubic244** [T3aHat/DeepLopener#5]
数日前より使用させて頂き大変便利で助かっております

DeepL openerを有効にすると翻訳機能未使用時でも表示が崩れるページがあります
現在発生確認しているのはzabbix管理画面のみです

DeepL openerの有効無効時の画像
無効: https://i.gyazo.com/372a89e196a4a2b709ff1701e2811775.png
有効: https://i.gyazo.com/7f1b730749736680524304bae8dab2a3.png

「injected stylesheet」により属性が上書きされ崩れてしまうようです
表示の崩れだけのようなので致命的な問題ではありません

----

Chrome バージョン: 91.0.4472.77（Official Build） （64 ビット）
DeepL opener バージョン: 1.1.6 (Chrome ウェブストアよりインストール) オプション 日本語 Eneble Eneble Free

**Comment by T3aHat** [comment]
ご報告ありがとうございます．  
本問題は本来PDFモードでしか用いられない`jquery-ui.css`をすべてのページ(URL)に対して適用していたことが原因だと考えられます．  
従って，`jquery-ui.css`および`jquery-ui.js`を挿入する対象をPDFのページに限定するようver.1.1.7 ( 75c4a489f54249131d371775cd21ebc71fb7a383) として実装しました．  
これにより本現象は改善されると思いますが，追加のpermissionsに`<all_urls>`が追加されることとなりました．

**Comment by T3aHat** [comment]
私の感覚的には`activeTab`権限で十分だと思うのですが，この場合`Unchecked runtime.lastError: Cannot access contents of the page. Extension manifest must request permission to access the respective host.`が出てJSを挿入できなかったので，このような実装となっています．

**Comment by cubic244** [comment]
該当ページの問題解消致しました

権限に関しては、更新時に追加権限の許可表示等はなかったので、強い権限ではないと思われますのであまり気にする必要もないのかなと素人考えでは思います

素早い対応ありがとうございました
