### ISSUE TITLE
Issue with the "do you want to translate this page?" prompt

### ISSUE THREAD

**Issue by Zero3K** [T3aHat/DeepLopener#6]
The box that contains it is too small, which causes the buttons to click to not be showing.

**Comment by T3aHat** [comment]
I have not been able to reproduce this problem.
If you can provide a detailed runtime and screenshot, it might help.

**Comment by T3aHat** [comment]
Changed alert() to be fired by ContentsScript instead of Popup (dd3d7faef0d6b9710ea763c6c97ce5df70f6ef63).
