### ISSUE TITLE
Some sites (such as live.fc2.com) get messed up when translating the page

### ISSUE THREAD

**Issue by Zero3K** [T3aHat/DeepLopener#7]
*subject*

**Comment by T3aHat** [comment]
I have also confirmed that I can't use page translation not only on live.fc2.com but also on yahoo.co.jp. 
This is commonly caused by the following error related to CORS.
```
Access to fetch at 'https://api-free.deepl.com/v2/translate' from origin 'https://www.yahoo.co.jp' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```
I have no plans to fix this problem. Please use the layout-oriented replacement mode instead, which does not cause such errors.
