### ISSUE TITLE
Font styling isn't being applied to translated text

### ISSUE THREAD

**Issue by Zero3K** [T3aHat/DeepLopener#8]
Please fix it so that it does.

**Comment by T3aHat** [comment]
Please show us an example image and web page where the font does not change.
At least on [this web page](https://developers.google.com/fonts), the font appears to be applied correctly.  
![image](https://user-images.githubusercontent.com/36735403/128052854-411805b0-bdb5-451b-b731-41e2e4ba55bc.png)
↑Original text
![image](https://user-images.githubusercontent.com/36735403/128052917-c0c1c7f7-b955-4a32-b24b-be5c6ced6874.png)
↑EN→FR on layout-oriented replacement mode
![image](https://user-images.githubusercontent.com/36735403/128052967-08be2e1c-ace5-4a92-8dce-143a7db9850b.png)
↑EN→FR on text-oriented replacement mode
